config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'users/registrations',
   sessions: 'users/sessions',
   omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'homes#top'
  get 'about' => 'homes#about'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'search' => 'searches#index'
  # get 'edit' => 'searches#edit'
  resources :trends, only: [:index]
  # resources :searches, only: [:edit]
  resources :tabs, only: [:create, :update]
  resources :keywords, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :update]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :tabs, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end


  protected
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        email: User.dumy_email(auth),
        provider: auth.provider,
        uid: auth.uid,
        password: Devise.friendly_token[0, 20],
        nickname: auth.info.nickname,
        image: auth.info.image
      )
    end
    user
  end


  private

  def self.dumy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  def twitter
    callback_from :twitter
  end


  private

  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: provider.capitalize
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.#{provider}_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # after_action :tab_create, only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  #   resource.tabs.build
  #   resource.tabs.name = 'タブ'
  #   resource.save
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


  private

  def after_update_path_for(resource)
   user_path(resource)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストとしてログインしました。'
  end

  def create
    # request.env['omniauth.auth']にユーザのTwitter認証情報が格納されている
    if user_data = request.env['omniauth.auth']
      session[:nickname] = user_data[:info][:nickname]
      redirect_to root_path, notice: 'ログインしました'
    end
    super
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
  end

  def update

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">
  <div class="row my-3 justify-content-center">
    <%= render 'layouts/main_head' %>
  </div>

  <div class="row mt-5 justify-content-center">
    <div class="card mx-auto p-5">
      <div class="mx-auto">
        <h2 class="mb-4">ユーザー情報</h2>
      </div>
      <div class="mx-md-5">
        <% if current_user.uid.nil? %>
          <% if current_user.email == 'guest@example.com' %>
          <!-- ゲストユーザー -->
            <p>ゲストユーザーです</p>
          <% else %>
          <!-- メアドログインユーザー -->
            <p>登録メールアドレス：<%= current_user.email %></p>
            <p>パスワード：●●●●●●</p>
            <%= link_to edit_user_registration_path(), class: "btn btn-outline-success" do %>
              編集
            <% end %>
          <% end %>
        <% else %>
          <!-- Twitterログインユーザー -->
          <h6>Twitterでログイン中です。</h6>
          <div class="mb-5">
            <div>
              <div class="mr-2">
                ログインアカウント：
                <%= link_to 'https://twitter.com/#{[:nickname]}', class: "btn btn-outline-secondary pl-0 py-0 pr-3" do %>
                  <% if current_user.image.nil? %>
                    <!-- Twitter画像なし -->
                    <span class="mx-2"><i class="fas fa-user"></i></span>
                    <span><%= current_user.nickname %></span>
                  <% else %>
                    <!-- Twitter画像あり -->
                    <span><%= image_tag(current_user.image,class: "", style: "height:") %></span>
                    <span class="mx-2"><%= current_user.nickname %></span>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <h5 class="mb-1">比べたter のアカウントを削除</h5>
          <span class="my-0">Twitterアカウントは削除されません。</span>
          <p><%= button_to "アカウント削除", registration_path(current_user), data: { confirm: "本当に削除しますか?" }, method: :delete, class: "btn btn-danger px-2" %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>