config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'users/registrations',
   sessions: 'users/sessions',
   omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'homes#top'
  get 'about' => 'homes#about'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'search' => 'searches#index'
  # get 'edit' => 'searches#edit'
  resources :trends, only: [:index]
  # resources :searches, only: [:edit]
  resources :tabs, only: [:create, :update]
  resources :keywords, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :update]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  def index
    client = Twitter::REST::Client.new do |config|
      # 事前準備で取得したキーのセット
      config.consumer_key = ENV['API_KEY']
      config.consumer_secret = ENV['API_KEY_SECRET']
      config.access_token = ENV['ACCESS_TOKEN']
      config.access_token_secret = ENV['ACCESS_TOKEN_SECRET']
    end

    @trends = client.trends(id = 23424856).attrs[:trends].first(30)
  end
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/trends/index.html.erb
<div class="container">
  <div class="row my-3 justify-content-center">
    <%= render 'layouts/main_head' %>
  </div>

  <div class="row">
    <h2 class="col-12 my-3">トレンドトップ30</h2>
    <div class="col-md-6">
      <table class="table table-hover table-inverse">
        <tbody>
          <% @trends.each_with_index do |trend, i| %>
            <% if i >= 15 %>
              <% break %>
            <% else %>
              <tr>
                <td class="px-0">
                  <%= i+1 %>.
                </td>
                <td class="pl-0">
                  <a href="<%= trend[:url] %>" class=""> <%= trend[:name] %> </a>
                </td>
                <td class="pl-0 tw_tr_count d-flex justify-content-end">
                  <% if trend.stringify_keys['tweet_volume'].present? %>
                    <%= trend.stringify_keys['tweet_volume'].to_s(:delimited) %> 件のツイート
                  <% end %>
                </td>
                <td class="px-0" style="width:35px;">
                  <%= link_to search_path(keyword: trend[:name]), class: "btn btn-sm btn-outline-secondary" do %>
                    <i class="fa fa-chart-line"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-6">
      <table class="table table-hover table-inverse">
        <tbody>
          <% @trends.each_with_index do |trend, i| %>
            <% if i <= 14 %>
              <% next %>
            <% else %>
              <tr>
                <td class="px-0">
                  <%= i+1 %>.
                </td>
                <td class="pl-0">
                  <a href="<%= trend[:url] %>" class=""> <%= trend[:name] %> </a>
                </td>
                <td class="pl-0 tw_tr_count d-flex justify-content-end">
                  <% if trend.stringify_keys['tweet_volume'].present? %>
                    <%= trend.stringify_keys['tweet_volume'].to_s(:delimited) %> 件のツイート
                  <% end %>
                </td>
                <td class="px-0" style="width:35px;">
                  <a class="btn btn-sm btn-outline-secondary" href="/search?keyword=<%= trend[:name] %>"><i class="fa fa-chart-line"></i></a>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>