config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   registrations: 'users/registrations',
   sessions: 'users/sessions',
   omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'homes#top'
  get 'about' => 'homes#about'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'search' => 'searches#index'
  # get 'edit' => 'searches#edit'
  resources :trends, only: [:index]
  # resources :searches, only: [:edit]
  resources :tabs, only: [:create, :update]
  resources :keywords, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :update]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="my-3 d-flex justify-content-center">
    <p>&copy; YukenHaranaka 2023</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark shadow-sm">
    <div class="container">
      <a class="navbar-brand p-0" href="/"><span><%= image_tag 'logo1_n.png', size: "60x50" %></span></a>
      <button class="navbar-toggler bg-secondary" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="mr-2">
            <%= link_to user_path(current_user),class: 'nav-link text-dark' do %>
              <% if current_user.uid.nil? %>
                <% if current_user.email == 'guest@example.com' %>
                  <i class="fas fa-user"></i> ゲスト
                <% else %>
                  <i class="fas fa-user"></i> ユーザー
                <% end %>
              <% else %>
                <% if current_user.image.nil? %>
                  <i class="fas fa-user"></i> <%= current_user.nickname %>
                <% else %>
                  <div>
                    <div class="rounded-circle mr-2">
                      <%= image_tag(current_user.image,class: "tw_img rounded-circle", style: "height:30px") %>
                      <%= current_user.nickname %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </li>
          <li class="log_out">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
          <li>
            <%= link_to 'ゲストログイン', users_guest_sign_in_path, class: "nav-link text-dark sign_in", method: :post %>
          </li>
          <li>
            <%= link_to user_twitter_omniauth_authorize_path, method: :post , data: { turbo: false }, class: "twitter_log nav-link text-info" do %>
                <div><i class="fab fa-twitter"></i> Twitterでログイン</div>
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_main_head.html.erb
<a href="/trends" class="btn btn-info rounded-pill d-flex align-items-center mr-3"><span>トレンド</span></a>
<a href="/search" class="btn btn-info rounded-pill d-flex align-items-center ml-3"><span>気になるワード<span></span></a>
<div class="ml-md-5 mt-2">
    <%= form_with url: "/search",method: :get, class: "" do |f| %>
      <%= f.text_field :keyword, required: true %>
      <button title="検索" type="submit" class="px-2">検索</button>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>比べたter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/header' %>

    <main>
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <i class="fas fa-check-circle"></i><span class="ml-2"><%= notice %></span>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <i class="fas fa-exclamation-triangle"></i><span class="ml-2"><%= alert %></span>
        </div>
      <% end %>

      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>